#!/bin/bash

# Loop through all files in articles/dev directory
for file in articles/dev/*
do
    # Check if file doesn't begin with four dashes
    if [[ $(head -n 1 "$file") != "----"* ]]
    then
        # Prepend file with line containing four dashes and current time
        sed -i "1i---- $(date)" "$file"
        # Stage the modified file
        git add "$file"
    fi

done